name: kisukinen
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  
  # AppWrite
  appwrite: ^13.0.0


  # firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  firebase_app_check: ^0.3.1+7
  cloud_firestore: ^5.6.0

  # font
  google_fonts: ^6.2.1

  # icon
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6
  random_avatar: ^0.0.8
  flutter_rating_bar: ^4.0.1


  # utils
  provider: ^6.1.2
  flutter_overlay_loader: ^2.0.0
  google_nav_bar: ^5.0.6
  stylish_bottom_bar: ^1.1.0
  intl: ^0.20.1
  image_picker: ^1.1.0
  iconsax: ^0.0.8
  carousel_slider: ^5.0.0
  lottie: ^3.1.3
  connectivity_plus: ^6.1.1
  loading_animation_widget: ^1.3.0
  

  #state management
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/google.png
    - assets/facebook.png
    - assets/email.png
    - assets/mascot.png
    - assets/male_tshirt.jpeg
    - assets/male_shirt.jpg
    - assets/banner/
    - assets/product_photos/

